#!/usr/bin/env python3
"""Pack a set of directory trees into a self-contained C++ translation unit.

Usage:
    make_embedded_assets.py <out.cpp> <srcDir>=<destDir> [<srcDir>=<destDir> ...]

Every file under each <srcDir> is embedded as raw bytes and exposed through
kimia::embedded::assetList() with its path relative to <destDir>. The engine
unpacks them at runtime so a single .exe / .apk runs with nothing next to it.

This is the "Unity-style" packing step: build-time assets become part of the
binary, and the runtime extracts them once into a writable cache directory.
"""
import os
import sys


def main():
    if len(sys.argv) < 3:
        sys.stderr.write(__doc__)
        return 2

    out_cpp = sys.argv[1]
    mappings = sys.argv[2:]

    entries = []  # (path_in_binary, raw_bytes)
    for mapping in mappings:
        if "=" not in mapping:
            sys.stderr.write("bad mapping (expected src=dest): %s\n" % mapping)
            return 2
        src, dest = mapping.split("=", 1)
        if not os.path.isdir(src):
            sys.stderr.write("skip missing dir: %s\n" % src)
            continue
        for dirpath, dirnames, filenames in os.walk(src):
            dirnames.sort()
            for filename in sorted(filenames):
                full = os.path.join(dirpath, filename)
                rel = os.path.relpath(full, src).replace("\\", "/")
                with open(full, "rb") as f:
                    data = f.read()
                entries.append((dest.rstrip("/") + "/" + rel, data))

    entries.sort(key=lambda e: e[0])

    with open(out_cpp, "w", encoding="utf-8") as f:
        f.write("// Generated by Tools/make_embedded_assets.py — do not edit.\n")
        f.write("#include <kimia/EmbeddedAssets.h>\n\n")
        f.write("namespace kimia { namespace embedded {\n\n")
        f.write("static const unsigned char kBlob[] = {\n")
        for path, data in entries:
            f.write("  // %s (%d bytes)\n" % (path, len(data)))
            for i in range(0, len(data), 24):
                chunk = data[i:i + 24]
                f.write("  " + ",".join(str(b) for b in chunk) + ",\n")
        f.write("};\n\n")
        f.write("static const Asset kAssets[] = {\n")
        offset = 0
        for path, data in entries:
            f.write('  {"%s", kBlob + %d, %d},\n' % (path, offset, len(data)))
            offset += len(data)
        f.write("  {nullptr, nullptr, 0},\n")
        f.write("};\n\n")
        f.write("const Asset* assetList() { return kAssets; }\n\n")
        f.write("} }  // namespace kimia::embedded\n")

    total = sum(len(d) for _, d in entries)
    print("embedded %d files, %d bytes -> %s" % (len(entries), total, out_cpp))
    return 0


if __name__ == "__main__":
    sys.exit(main())
